name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
jobs:
  main:
    name: Nx Cloud - Main
    permissions:
      id-token: write
      contents: write
      actions: read
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      pnpm-version: 8.11
      node-version: 20.10.0
      number-of-agents: 4
      main-branch-name: 'main'
      init-commands: |
        npx nx-cloud record -- pnpm exec prettier . --ignore-path .ci.prettierignore --check
      parallel-commands-on-agents: |
        pnpm exec nx run-many --target=lint --parallel=4
        pnpm exec nx run-many --target=build --parallel=4
        pnpm exec nx run-many --target=test --parallel=4

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 4
      pnpm-version: 8.11
      node-version: 20.10.0
